services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '9081:81'
      - '9080:80'
      - '9443:443'
    volumes:
      - ./nginx-data:/data:z
      - ./letsencrypt:/etc/letsencrypt:z

  ssoalert:
    build: ./
    container_name: sso-alert-pod
    ports:
      - "8080:8080"
    volumes:
      - ../sso_tom:/code:z
    depends_on:
      - db
    env_file: ../sso_tom/.env

  db:
    image: postgres:12.1
    container_name: postgres-pod
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data:z
    env_file: ../sso_tom/.env
